# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Amanda Sposito"
description: > # this means to ignore newlines until "email:"
   Software Engineer at Bleacher Report.
email: "hello@amandasposito.com"

#blog logo
logo: "/assets/images/icon.jpg"
icon: "/assets/images/icon.png"

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Amanda Sposito'
author: 'Amanda Sposito'
author_image: "/assets/images/author.jpg"

paginate:	20

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amandasposito.com" # the base hostname & protocol for your site
#used to display twitter cards
twitter_handle: '@amsposito'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/amsposito

  - icon:	github
    url:	https://github.com/amandasposito

  - icon: linkedin
    url:  https://www.linkedin.com/in/amandasposito
